In [1]:
import pandas as pd
df=pd.read_csv("C:\\Users\\malat\\OneDrive\\Desktop\\MutualFundAnalysis\\data\\raw\\01_fund_master.csv")
print("Shape:", df.shape)
print(df.dtypes)
df.head()

Shape: (40, 15)
amfi_code               int64
fund_house             object
scheme_name            object
category               object
sub_category           object
plan                   object
launch_date            object
benchmark              object
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager           object
risk_category          object
sebi_category_code     object
dtype: object

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [2]:
import pandas as pd
df=pd.read_csv("C:\\Users\\malat\\OneDrive\\Desktop\\MutualFundAnalysis\\data\\raw\\02_nav_history.csv")
print("Shape:", df.shape)
print(df.dtypes)
df.head()

Shape: (46000, 3)
amfi_code      int64
date          object
nav          float64
dtype: object

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [3]:
import pandas as pd
df=pd.read_csv("C:\\Users\\malat\\OneDrive\\Desktop\\MutualFundAnalysis\\data\\raw\\03_aum_by_fund_house.csv")
print("Shape:", df.shape)
print(df.dtypes)
df.head()

Shape: (90, 5)
date               object
fund_house         object
aum_lakh_crore    float64
aum_crore           int64
num_schemes         int64
dtype: object

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

In [4]:
import pandas as pd
df=pd.read_csv("C:\\Users\\malat\\OneDrive\\Desktop\\MutualFundAnalysis\\data\\raw\\04_monthly_sip_inflows.csv")
print("Shape:", df.shape)
print(df.dtypes)
df.head()

Shape: (48, 6)
month                         object
sip_inflow_crore               int64
active_sip_accounts_crore    float64
new_sip_accounts_lakh        float64
sip_aum_lakh_crore           float64
yoy_growth_pct               float64
dtype: object

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN

In [5]:
import pandas as pd
df=pd.read_csv("C:\\Users\\malat\\OneDrive\\Desktop\\MutualFundAnalysis\\data\\raw\\05_category_inflows.csv")
print("Shape:", df.shape)
print(df.dtypes)
df.head()

Shape: (144, 3)
month                object
category             object
net_inflow_crore    float64
dtype: object

     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

In [6]:
import pandas as pd
df=pd.read_csv("C:\\Users\\malat\\OneDrive\\Desktop\\MutualFundAnalysis\\data\\raw\\06_industry_folio_count.csv")
print("Shape:", df.shape)
print(df.dtypes)
df.head()

Shape: (21, 6)
month                   object
total_folios_crore     float64
equity_folios_crore    float64
debt_folios_crore      float64
hybrid_folios_crore    float64
others_folios_crore    float64
dtype: object

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01,13.26,9.28,1.86,0.80,1.33
1,2022-04,13.91,9.74,1.95,0.83,1.39
2,2022-07,13.85,9.69,1.94,0.83,1.38
3,2022-10,14.12,9.88,1.98,0.85,1.41
4,2023-01,14.81,10.37,2.07,0.89,1.48

In [8]:
import pandas as pd
df=pd.read_csv("C:\\Users\\malat\\OneDrive\\Desktop\\MutualFundAnalysis\\data\\raw\\07_scheme_performance.csv")
print("Shape:", df.shape)
print(df.dtypes)
df.head()

Shape: (40, 19)
amfi_code               int64
scheme_name            object
fund_house             object
category               object
plan                   object
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade             object
dtype: object

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [9]:
import pandas as pd
df=pd.read_csv("C:\\Users\\malat\\OneDrive\\Desktop\\MutualFundAnalysis\\data\\raw\\09_portfolio_holdings.csv")
print("Shape:", df.shape)
print(df.dtypes)
df.head()

Shape: (322, 8)
amfi_code              int64
stock_symbol          object
stock_name            object
sector                object
weight_pct           float64
market_value_cr      float64
current_price_inr    float64
portfolio_date        object
dtype: object

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

In [10]:
import pandas as pd
df=pd.read_csv("C:\\Users\\malat\\OneDrive\\Desktop\\MutualFundAnalysis\\data\\raw\\10_benchmark_indices.csv")
print("Shape:", df.shape)
print(df.dtypes)
df.head()

Shape: (8050, 3)
date            object
index_name      object
close_value    float64
dtype: object

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

In [11]:
import requests
import pandas as pd
url = "https://api.mfapi.in/mf/125497"
response = requests.get(url)
data = response.json()
print(data.keys())
nav_df = pd.DataFrame(data["data"])
nav_df.head()

dict_keys(['meta', 'data', 'status'])

         date        nav
0  19-06-2026  202.07610
1  18-06-2026  200.95650
2  17-06-2026  199.83020
3  16-06-2026  198.61520
4  15-06-2026  198.03200

In [12]:
nav_df.to_csv("C:\\Users\\malat\\OneDrive\\Desktop\\MutualFundAnalysis\\data\\raw\\hdfc_top100_direct.csv",
              index=False)

print("CSV saved successfully")

CSV saved successfully

In [13]:
import requests
import pandas as pd

schemes = {
    "SBI_Bluechip": 119551,
    "ICICI_Bluechip": 120503,
    "Nippon_Large_Cap": 118632,
    "Axis_Bluechip": 119092,
    "Kotak_Bluechip": 120841
}

In [14]:
for fund_name, scheme_code in schemes.items():

    url = f"https://api.mfapi.in/mf/{scheme_code}"
    response = requests.get(url)
    data = response.json()
    nav_df = pd.DataFrame(data["data"])
    file_path = rf"C:\Users\malat\OneDrive\Desktop\MutualFundAnalysis\data\raw\{fund_name}.csv"
    nav_df.to_csv(file_path, index=False)
    print(f"{fund_name} saved successfully")

SBI_Bluechip saved successfully
ICICI_Bluechip saved successfully
Nippon_Large_Cap saved successfully
Axis_Bluechip saved successfully
Kotak_Bluechip saved successfully

In [15]:
"""Explore Fund Master"""
import pandas as pd

fund_master = pd.read_csv(
    r"C:\Users\malat\OneDrive\Desktop\MutualFundAnalysis\data\raw\01_fund_master.csv"
)

fund_master.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [17]:
"""Unique Fund Houses"""
print(fund_master['fund_house'].unique())

['SBI Mutual Fund' 'HDFC Mutual Fund' 'ICICI Prudential MF'
 'Nippon India MF' 'Kotak Mahindra MF' 'Axis Mutual Fund'
 'Aditya Birla Sun Life MF' 'UTI Mutual Fund' 'Mirae Asset MF'
 'DSP Mutual Fund']

In [18]:
"""Unique Categories"""
print(fund_master['category'].unique())

['Equity' 'Debt']

In [19]:
"""Unique Sub_Categories"""
print(fund_master['sub_category'].unique())

['Large Cap' 'Small Cap' 'Gilt' 'Mid Cap' 'Short Duration' 'Value'
 'Liquid' 'Index/ETF' 'Flexi Cap' 'Index' 'Large & Mid Cap' 'ELSS']

In [20]:
"""Unique Risk Grades"""
print(fund_master['risk_category'].unique())

['Moderate' 'Very High' 'Low' 'High' 'Moderately High']

In [21]:
"""Understand AMFI Scheme Codes"""
fund_master[['amfi_code','scheme_name']].head(20)

    amfi_code                                        scheme_name
0      119551          SBI Bluechip Fund - Regular Plan - Growth
1      119552           SBI Bluechip Fund - Direct Plan - Growth
2      119598         SBI Small Cap Fund - Regular Plan - Growth
3      119599          SBI Small Cap Fund - Direct Plan - Growth
4      119120       SBI Magnum Gilt Fund - Regular Plan - Growth
5      100016          HDFC Top 100 Fund - Regular Plan - Growth
6      125497           HDFC Top 100 Fund - Direct Plan - Growth
7      100033  HDFC Mid-Cap Opportunities Fund - Regular - Gr...
8      125498  HDFC Mid-Cap Opportunities Fund - Direct - Growth
9      100025       HDFC Short Term Debt Fund - Regular - Growth
10     120503         ICICI Pru Bluechip Fund - Regular - Growth
11     120504          ICICI Pru Bluechip Fund - Direct - Growth
12     120505           ICICI Pru Midcap Fund - Regular - Growth
13     120506  ICICI Pru Value Discovery Fund - Regular - Growth
14     120507           ICICI Pru Liquid Fund - Regular - Growth
15     118632     Nippon India Large Cap Fund - Regular - Growth
16     118633      Nippon India Large Cap Fund - Direct - Growth
17     118634     Nippon India Small Cap Fund - Regular - Growth
18     118635                     Nippon India ETF Nifty 50 BeES
19     118636  Nippon India Gilt Securities Fund - Regular - ...

In [22]:
"""Validate AMFI Codes"""
nav_history = pd.read_csv(
    r"C:\Users\malat\OneDrive\Desktop\MutualFundAnalysis\data\raw\02_nav_history.csv")

In [23]:
print("Fund Master Rows:", fund_master.shape)
print("NAV History Rows:", nav_history.shape)

Fund Master Rows: (40, 15)
NAV History Rows: (46000, 3)

In [24]:
"""Check missing AMFI codes"""
master_codes = set(fund_master['amfi_code'])
nav_codes = set(nav_history['amfi_code'])
missing_codes = master_codes - nav_codes
print("Missing Codes:", len(missing_codes))
print(missing_codes)

Missing Codes: 0
set()

In [25]:
"""Data Quality Checks"""
"""Missing values"""
print(fund_master.isnull().sum())

amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

In [26]:
print(nav_history.isnull().sum())

amfi_code    0
date         0
nav          0
dtype: int64

In [27]:
"""Duplicates"""
print("Fund Master Duplicates:",
      fund_master.duplicated().sum())

Fund Master Duplicates: 0

In [28]:
print("NAV History Duplicates:",
      nav_history.duplicated().sum())

NAV History Duplicates: 0

In [29]:
print(fund_master.columns)

Index(['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category',
       'plan', 'launch_date', 'benchmark', 'expense_ratio_pct',
       'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager',
       'risk_category', 'sebi_category_code'],
      dtype='object')

In [30]:
print(nav_history.columns)

Index(['amfi_code', 'date', 'nav'], dtype='object')

In [31]:
"""Validate AMFI Codes"""
master_codes = set(fund_master['amfi_code'])
nav_codes = set(nav_history['amfi_code'])
missing_codes = master_codes - nav_codes
print("Total Fund Master Codes:", len(master_codes))
print("Total NAV History Codes:", len(nav_codes))
print("Missing Codes:", len(missing_codes))

Total Fund Master Codes: 40
Total NAV History Codes: 40
Missing Codes: 0

In [32]:
print(missing_codes)

set()